### ISSUE TITLE
LSPService running but not detected by Codeface

### ISSUE THREAD

**Issue by thistlillo** [codeface-io/LSPService#3]
I have installed Codeface ver. 1.3.4 (20) on Mac OS Ventura 13.0.1 plus the LSPService
There is no (and there will be no) Xcode installation. 

LSPService, installed according to instructions, seems to start without errors:
```
-> ./LSPService
[ NOTICE ] Server starting on http://127.0.0.1:8080
```

When I start CodeFace (with the LSPService running), I get his:
<img width="803" alt="Screenshot 2022-12-08 at 17 18 30" src="https://user-images.githubusercontent.com/6717655/206502814-feebdda8-a8d8-4b40-925a-6c9d25d810c6.png">

It says that the LSPService is not running. Actually, the LSP Service receives requests from CodeFace. When the latter starts, I see these log messages:
```
$-> ./LSPService
[ NOTICE ] Server starting on http://127.0.0.1:8080
[ INFO ] GET /lspservice/api/processID [request-id: 3A0132E3-C6BB-4613-A88C-5269D040B94C] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 3A0132E3-C6BB-4613-A88C-5269D040B94C] (Vapor/Middleware/ErrorMiddleware.swift:42)
```
If I press the "Check again" button in CodeFace, the LSPService prints out other messages (the same as before but with a different `request-id`).

I have also modified the `LSPServiceConfig.json` replacing its content with or appending the Java LSP server:
```
{
  "java" : {
    "path" : "/Users/user/Apps/LanguageServers/jdt-language-server-1.19.0/bin/jdtls",
    "arguments" : [
    ],
    "environment" : {
    }
  }
}
```
but, still, CodeFace does not detect the running `LSPService` instance.

Question: what am I doing wrong? What should I do to connect Codeface and the LSP Service?

**Comment by codeface-io** [comment]
Hello there!

Thanks for reaching out!

I think you're doing everything right 😊 Codeface will probably find your running LSPService when importing a Java folder. Only the convenience of reporting whether LSPService is running is broken.

I think I accidentally pushed the new (and in this case breaking) binaries of LSPService too early. But I just submitted an update of Codeface. It works with the new LSPService and should be in the Store within 24 hours.

An underlying issue here is the lacking versioning system to match up Codeface and LSPService. For context, have a look at the LSPService roadmap: Versioning is the very next task. But if the current task would have succeeded (it seems now that's technically impossible), the versioning would have been unnecessary and we would have gotten rid of LSPService 😕

However, I can't say anything about the Java LSP server, since I haven't experimented with Java yet. Have you tried to import a Java-based project?

**Comment by thistlillo** [comment]
Hello @flowtoolz, 
 thank you for your fast and detailed answer. I did not try to import a Java folder, the (legacy) Java project is not currently on the Mac and I thought it would be useless to proceed due to that error. I discovered Codeface only yesterday and decided to give it a try to make sense of that old code, that is quite long to configure and set up running. I will try during the next days and report back here. 

Cheers

**Comment by thistlillo** [comment]
I have downloaded a sample project from GitHub. This is a very simple projects, with all source files in the same folder, specifically the `src` folder, that contains:
```
 8 -rw-r--r--  1 user  staff   830 Dec 10 19:49 Alphabet.java
16 -rw-r--r--  1 user  staff  6201 Dec 10 19:49 Generator.java
 8 -rw-r--r--  1 user  staff  1029 Dec 10 19:49 GeneratorTest.java
 8 -rw-r--r--  1 user  staff   280 Dec 10 19:49 Main.java
 8 -rw-r--r--  1 user  staff  2149 Dec 10 19:49 Password.java
```
After entering "java" and "java" for language and file endings ("java" is the key in the json dictionary LSPServiceConfig.json of the Java language server), Codeface displays:
<img width="400" alt="Screenshot 2022-12-10 at 19 57 49" src="https://user-images.githubusercontent.com/6717655/206871082-aebe37b0-75fc-416e-a63f-57c2be830573.png">

However, when I click on any of the files, there is not much besides warnings that should not be there:
<img width="700" alt="Screenshot 2022-12-10 at 19 59 37" src="https://user-images.githubusercontent.com/6717655/206871158-337a7dc3-1141-4cc3-9ddb-e3f1f1e76e78.png">

This is the log:
```
$-> ./LSPService
[ NOTICE ] Server starting on http://127.0.0.1:8080
[ INFO ] GET /lspservice/api/processID [request-id: 08A3808D-F550-4DDB-9431-AB4905C1BA43] (Vapor/RouteLoggingMiddleware.swift:13)
[ INFO ] GET /lspservice/api/language/java/websocket [request-id: E2D60544-C057-4135-ADCF-B1A619AEE9C8] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 08A3808D-F550-4DDB-9431-AB4905C1BA43] (Vapor/Middleware/ErrorMiddleware.swift:42)
ℹ️ Running LSP server /Users/user/Apps/LanguageServers/jdt-language-server-1.19.0/bin/jdtls
ℹ️ Java language server sent message via stdErr:
WARNING: Using incubator modules: jdk.incubator.concurrent, jdk.incubator.vector
[ INFO ] GET /lspservice/api/processID [request-id: 5C416746-DB12-47C8-823B-30DED23AE471] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 5C416746-DB12-47C8-823B-30DED23AE471] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 4C49A095-85BB-4F34-AD67-7EE801BBCA1A] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 4C49A095-85BB-4F34-AD67-7EE801BBCA1A] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 42F9521D-AAD1-4C66-80FE-16DE8096568D] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 42F9521D-AAD1-4C66-80FE-16DE8096568D] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: CA520F65-5F40-46C5-808C-E71EEB49B1CA] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: CA520F65-5F40-46C5-808C-E71EEB49B1CA] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: DE944E14-737B-4E91-9524-11A87D3A1A3B] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: DE944E14-737B-4E91-9524-11A87D3A1A3B] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 35935E62-B9F4-43D8-B030-D70F808BAB10] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 35935E62-B9F4-43D8-B030-D70F808BAB10] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 300EA3B4-FF81-4DE6-B473-EE1AFF7A9C67] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 300EA3B4-FF81-4DE6-B473-EE1AFF7A9C67] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 0CDB61DD-B179-48B0-9890-6E72E8AA0EF1] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 0CDB61DD-B179-48B0-9890-6E72E8AA0EF1] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ INFO ] GET /lspservice/api/processID [request-id: 654AD38F-F94A-4E4E-B8C6-7EBA4DA0A333] (Vapor/RouteLoggingMiddleware.swift:13)
[ DEBUG ] RouteNotFound.404: Not Found [request-id: 654AD38F-F94A-4E4E-B8C6-7EBA4DA0A333] (Vapor/Middleware/ErrorMiddleware.swift:42)
```

I have a question. Let's say that Codeface works fine on this Java project. Real projects contain Java source code  organised in folders that correspond to packages. For example, the class `Tokenize` of package `app_name.utilities.text` would correspond to `Tokenize.java` in folder `app_name/utilities/text`. I does not seem Codeface would import the source files recursively visiting the initial folder (in this case `app_name`). Am I wrong?

**Comment by codeface-io** [comment]
Hey there!

Generally, if you don't even see the symbols within files, using the LSP server certainly did not work.

In your case, either Codeface or LSPService is not up to date. The latest versions do not use the `/lspservice/api/processID` endpoint anymore. Also, the "Check Again" should work.

As soon as Codeface can talk to the LSP server (which it does in your case since you get `ℹ️ Java language server sent message via stdErr:`), the whole issue becomes knowing how to use the LSP server. I'm admittedly no Java programmer and don't know how the Java LSP server works.

> Real projects contain Java source code organised in folders that correspond to packages. For example, the class Tokenize of package app_name.utilities.text would correspond to Tokenize.java in folder app_name/utilities/text. I does not seem Codeface would import the source files recursively visiting the initial folder (in this case app_name). Am I wrong?

When you select a code folder in Codeface, you should select one that is considered (and your LSP server considers) a project folder. Codeface will recursively detect and show all folders and all files with the ending(s) you provided. What dependencies and symbols you see within that file system structure depends on the capabilities of your LSP server.

All of that said, I'm really excited to get a Java project working with Codeface! Most users are still in the Swift realm ... If you provide me links to the same LSP server and example project, I'll try to reproduce your use case on my machine 😊

**Comment by thistlillo** [comment]
I updated Codeface and downloaded the LSPService from the updated menu: now relations among classes are shown. Great! 👏 

<img width="1509" alt="Screenshot 2022-12-13 at 07 28 39" src="https://user-images.githubusercontent.com/6717655/207243165-2d2bf410-dda0-4572-8daf-0aaebda42464.png">

This is the LSPService.zip I have used (downloaded via your updated app):
[LSPService.zip](https://github.com/codeface-io/LSPService/files/10215091/LSPService.zip)

The Java language server is:
https://download.eclipse.org/jdtls/milestones/1.9.0/
(reached starting from: https://langserver.org/)

The simple Java project is this (chosen randomly for the initial test):
https://github.com/KZarzour/Password-Generator

Codeface is version: 1.3.5 (24)

I am going to test Codeface with my projects very soon. I will keep you posted.

Thank you!
